### ISSUE TITLE
Shifted video 

### ISSUE THREAD

**Issue by sashazxtt** [davedoesdev/webm-muxer.js#13] opened 2021-09-08 02:01 UTC
I produce a webm file that starts off with audio only. After 15 seconds I start producing video chunks. Everything looks fine - no errors from the muxer.
But looking at the file using ffprobe (and indeed, just playing it), the video starts at the same time as the audio - at the time zero.

So, the question is - is what I'm doing allowed? Or is there a bug in the muxer?

Thanks!

**Comment by davedoesdev** [comment] 2021-09-08 05:35
Ah yes I hadn't considered that use case, thanks for raising the issue!
At the moment, I use the first video chunk received as 0 and then use the durations to calculate the timestamps (this is more reliable that the timestamps that WebCodecs generates).
I wonder what's the best way to support this use case. I've found the timestamps for audio and video don't use the same starting value so we can't do any correlation. A similar issue is probably going to occur if the video is paused intermittently.
One option might be to allow the app to force using timestamps (if it knows it won't be producing continuous audio and video) and to get WebCodecs to encode an initial chunk so we get the timestamp of the first chunk straight away.
Anyway, I'll try to repro first and then do some experiments, hopefully in the next couple of weeks.

**Comment by davedoesdev** [comment] 2021-09-08 06:14
Actually the duration method is only used for audio. The video uses offset from first timestamp.
I think encoding a throwaway first frame is probably going to be the best solution so as to get the base timestamp that the VideoEncoder is using.
For continuous audio, the duration method is the most accurate but if the app knows it's not going to be continuous then falling back to timestamps is going to be necessary.

@sashazxtt most likely the solution is going to require the app to pass in an option to indicate to the muxer that it shouldn't expect continuous audio/video. Do you think that would be okay for app authors?

**Comment by davedoesdev** [comment] 2021-09-08 07:36
Thinking again, I think this can be done without requiring an initial throwaway encoding.
There will be 3 new options to the muxer:

- `wait_for_initial_video` (default true): If false then don't wait to encode audio until first video frame has been received. When the first video frame arrives, it will get the same timestamp that the last audio chunk got.  Use this if the video is expected to be delayed after the audio starts.
- `wait_for_initial_audio`: Same as above but other way around.
- `use_audio_timestamps`: Rely on AudioEncoder timestamps instead of calculating them using chunk duration. Use this when non-continuous audio is expected.

**Comment by sashazxtt** [comment] 2021-09-08 17:02
Thanks for considering this use case!
In fact, I do generate my own timestamps for both audio and video (in the encoder-worker) and provide them to the encoders.
Pausing/resuming and in fact stopping video track mid-stream and then starting a new one all works.
It is the case above that seems to be an issue. So far my plan to work around was to always insert a dummy video frame at the time zero, even if I don't expect video data to be present until some (possibly distant) point in a future. I've not tried this approach yet.
I think the options you propose above will work.
Another case that doesn't work is specifying that the file will have both audio and video tracks, but never giving it any video frames - nothing will be written to the file. I think this will be resolved with my idea of the workaround.

Regarding my own timestamps - I find that audio frames as read from the `readable` will have timestamps that may be rather far into the 'future' (as far as the recording is concerned; recordings' timestamps start at zero, but audio stream may be long-lived by the time recording starts, so its timestamp is unusable). As you suggest, using duration to calculate the timestamp or buffer size and sample frequency is a way to do it. I currently use the performance.now() deltas from a common audio and video start time (zero). The `timestamp` field of AudioFrame is immutable, so I create my own from the one obtained from the `readable` and provide my own timestamp.

Thanks!

p.s. I wanted to compliment you on starting and producing this library - it is well-designed  and very useful! I hope a lot of people will find it as useful as I have!

p.p.s If there was a way to fix the seekability issue as a finalization step without needing to read the whole file in that would be really nice. Maybe keep the cues section in memory and then write it out into the file's headers? I understand it can also be present at the end of a file, probably making it a bit simpler to implement as only a position would need to be updated in a header?

**Comment by sashazxtt** [comment] 2021-09-08 17:10
There is another issue I see, which may be same/similar.
1. Start recording with both audio and video
2. Stop video stream
3. Let record for a while
4. Stop recording
5. Play the recording
6. Observe that the file stops at the time of the step 2. Additional audio is not there.

Thanks!

**Comment by davedoesdev** [comment] 2021-09-08 18:03
That's strange because
https://github.com/davedoesdev/webm-muxer.js/blob/main/webm-worker.js#L254
should ensure pending data is sent to be muxed.

**Comment by sashazxtt** [comment] 2021-09-08 18:51
aha, i am not using the latest! will give it a try

**Comment by sashazxtt** [comment] 2021-09-08 20:12
Here is another bit of an under-surface stones:
`  while (queued_audio.length !== 0 && queued_video.length !== 0) {
    if (queued_audio[0].timestamp <= queued_video[0].timestamp) {
      send_msg(queued_audio.shift());
    } else {
      send_msg(queued_video.shift());
    }
  }`
In case if one of the streams fails for some reason (like I constantly see audio track stop on my VDI system out of the blue), the video will not be written to the file until the end, resulting in the growing memory use. Pretty quickly it can grow into gigabytes...

**Comment by davedoesdev** [comment] 2021-09-08 20:15
Yep, I was thinking that. The problem is I changed to this algorithm to fix some sync issues - relying on encoded audio and video arriving at the right time together wasn't reliable.
Perhaps a solution is to put a limit on the amount that can be buffered?

**Comment by sashazxtt** [comment] 2021-09-08 20:24
I think that the code you pointed me to in the handling of the `end` message will work in this place. I will give it a try :)

**Comment by davedoesdev** [comment] 2021-09-08 20:26
That code should make sure the stored data is flushed at the end but won't help during the stream/recording.

**Comment by davedoesdev** [comment] 2021-09-08 20:28
Btw I've implemented the options I described above but will make a test before pushing them.

Re indexing as the encoding progresses rather than at the end: I don't think I'll be able to do this as I'm using WebMLiveMuxer from webm-tools which doesn't support it.

**Comment by davedoesdev** [comment] 2021-09-08 20:32
I've opened https://github.com/davedoesdev/webm-muxer.js/issues/14 to track limiting size of queued data.

**Comment by sashazxtt** [comment] 2021-09-09 16:56
I've implemented inserting a placeholder frame in the beginning of the file. It seems to work OK, but VLC has a problem playing it out. 
If I start video 15 seconds into a recording, VLC will show black screen for 15 seconds, then flash the placeholder frame, then play the video.
Windows video player plays the video as expected (most of the time; it also sometimes fails - on the same file!).
Chrome plays it as expected.
Inspecting the packets with ffprobe shows expected timestamps for the video frames.

**Comment by davedoesdev** [comment] 2021-09-09 19:12
OK I've repro'd the issue so can do some testing now at least.

**Comment by davedoesdev** [comment] 2021-09-09 19:29
Hmm, even though I set the audio timestamps to be delayed (to where the video has reached), when I play the webm file the audio still starts straight away.

**Comment by davedoesdev** [comment] 2021-09-09 19:44
Ah, Ubuntu media player (totem I think) plays it correctly with audio starting later. ffplay plays the audio from the start.

**Comment by davedoesdev** [comment] 2021-09-09 20:18
VLC plays it correctly true. However, the fixups that I have to do to the timestamps if I don't buffer at all mean the metronome track I'm using isn't playing right.
EDIT: I think I have a bug, will try to look into it again in the next few days.

**Comment by sashazxtt** [comment] 2021-09-09 20:25
It seems that inserting five placeholder video frames in the beginning allows VLC to play the file as expected.

**Comment by davedoesdev** [comment] 2021-09-09 20:28
I didn't realise how flaky AV software is until I started this project :)

**Comment by sashazxtt** [comment] 2021-09-09 20:44
And it is much better than it was 15 years ago :)

**Comment by davedoesdev** [comment] 2021-09-10 05:24
@sashazxtt if you have time, could you try the `shifted-video` branch please: https://github.com/davedoesdev/webm-muxer.js/tree/shifted-video

There are 3 new options - search the README for `webm_options` which may help your use case.
Try setting `video_queue_limit` to something small like 30 to help with the audio starting later.
You can also try setting `use_audio_timestamps` to `true` if your audio is intermittent (though if it just ends early then it won't be necessary).

There's also a new demo, `media-element-demo.html`, which I've used to repro this issue.

**Comment by davedoesdev** [comment] 2021-09-11 06:52
`shifted-video` branch is now merged to main branch

**Comment by davedoesdev** [comment] 2021-09-14 05:21
@sashazxtt this works for me using the new options. Can you shift your video now?

**Comment by sashazxtt** [comment] 2021-09-14 06:29
Dave, I had this fixed the way I described - by refactoring the flushing code (queue draining you pointed out), writing a video placeholder frames (5) in case video starts later and my own audio and video timestamps.

Problem with timestamps coming from a reader is that they may be arbitrary - based on the duration of a stream at the time recording is starting. So, I always start at zero.

**Comment by davedoesdev** [comment] 2021-09-14 19:23
Cool. I'm using MediaStreamAudioDestinationNode and supplying silence when there's no audio from my app, and doing similar via a WebGL canvas for video.

Closing this issue. The extra options can be useful if the app wants some basic help with minimal effort I hope.

**Closed as completed by davedoesdev** 2021-09-14 19:23 UTC
Labels: bug
