### ISSUE TITLE
Investigate audio rate on recorded webm

### ISSUE THREAD

**Issue by davedoesdev** [davedoesdev/webm-muxer.js#6] opened 2021-08-03 07:47 UTC
Per #4 audio may be faster than expected in some cases.

**Comment by guest271314** [comment] 2021-08-03 14:26
Example 
[camera (7).webm.zip](https://github.com/davedoesdev/webm-muxer.js/files/6924814/camera.7.webm.zip)

**Comment by davedoesdev** [comment] 2021-08-06 09:04
Repro'd:

```
$ espeak-ng -w input.wav 'Test'
$ mediainfo input.wav 
General
Complete name                            : /home/david/Downloads/input.wav
Format                                   : Wave
File size                                : 28.3 KiB
Duration                                 : 656 ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 353 kb/s

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 656 ms
Bit rate mode                            : Constant
Bit rate                                 : 352.8 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 22.05 kHz
Bit depth                                : 16 bits
Stream size                              : 28.3 KiB (100%)
$ ./chrome --disable-features=AudioServiceOutOfProcess --use-fake-device-for-media-stream --use-file-for-fake-audio-capture=input.wav
# Run the demo and save webm
$ mkvinfo camera\ \(3\).webm 
+ EBML head
|+ EBML version: 1
|+ EBML read version: 1
|+ Maximum EBML ID length: 4
|+ Maximum EBML size length: 8
|+ Document type: webm
|+ Document type version: 4
|+ Document type read version: 2
+ Segment: size unknown
|+ Seek head (subentries will be skipped)
|+ Segment information
| + Duration: 00:00:06.600000000
| + Timestamp scale: 1000000
| + Multiplexing application: libwebm-0.3.0.0
| + Writing application: WebMLiveMuxer
|+ Tracks
| + Track
|  + Track number: 1 (track ID for mkvmerge & mkvextract: 0)
|  + Track UID: 64297900348418228
|  + Track type: video
|  + Codec ID: V_VP9
|  + Codec's private data: size 12
|  + Video track
|   + Pixel width: 1280
|   + Pixel height: 720
|   + Frame rate: 30
| + Track
|  + Track number: 2 (track ID for mkvmerge & mkvextract: 1)
|  + Track UID: 71664289764129580
|  + Track type: audio
|  + Seek pre-roll: 00:00:00.080000000
|  + Codec ID: A_OPUS
|  + Codec's private data: size 19
|  + Audio track
|   + Sampling frequency: 48000
|   + Channels: 1
|+ Cues (subentries will be skipped)
|+ Cluster

**Comment by davedoesdev** [comment] 2021-08-06 09:08
The sample rate (48000) is picked up from the track settings so the browser is either re-sampling or getting the sample rate wrong

**Comment by davedoesdev** [comment] 2021-08-06 09:13
https://bugs.chromium.org/p/chromium/issues/detail?id=421054 suggests file has to be 44.1kHz. Doesn't explain why Chrome is reporting it as 48kHz

**Comment by guest271314** [comment] 2021-08-06 14:22
WebCodecs `AudioDecoder` does that, too https://bugs.chromium.org/p/chromium/issues/detail?id=1236227#c2.

**Comment by guest271314** [comment] 2021-08-06 14:30
Note, the playback rate increase occasionally occurs with microphone input that is live, too - without using a fake capture device and stream.

**Comment by davedoesdev** [comment] 2021-08-07 10:44
What I don't understand is the file says it's 48000 but still plays fine using ffplay even though the input is 22050. Is Chrome actually resampling to 48000 for all inputs?

I've been trying to repro the rate change but still can't :(

**Comment by guest271314** [comment] 2021-08-07 14:33
>  Is Chrome actually resampling to 48000 for all inputs?

That appears to be the case, see https://bugs.chromium.org/p/chromium/issues/detail?id=1237633.

> I've been trying to repro the rate change but still can't :(

Did you not reproduce at https://github.com/davedoesdev/webm-muxer.js/issues/6#issuecomment-894117936?

**Comment by davedoesdev** [comment] 2021-08-07 14:47
Yes I did but it doesn't sound any different than the input

**Comment by guest271314** [comment] 2021-08-07 17:40
It occurred three times here during testing. I lost the first example and captured one test which was from `navigator.mediaDevices.getUserMedia({audio:true})`. I posted the result here so I would not potentially lost all test results.

**Comment by davedoesdev** [comment] 2021-08-07 17:48
Yes the file in the zip sounds fast when I play it. I'll try again to repro that when I get some time.

**Comment by davedoesdev** [comment] 2021-08-08 06:09
@guest271314 couple of questions:

- In camera (7).webm where is the video from? Just trying to get the same input.
- Have you had this issue since I fixed the private data?

**Comment by davedoesdev** [comment] 2021-08-08 07:00
I wonder if I should be using the timestamp properties on the WebCodec output at all but instead count the buffers?

**Comment by guest271314** [comment] 2021-08-08 14:14
> - In camera (7).webm where is the video from? Just trying to get the same input.

Web camera.

> - Have you had this issue since I fixed the private data?

I have not yet tested after the private data fix. (I have been busy in the field and testing WebTransport client and server.) I will download and test at least a few dozen times today.

**Comment by guest271314** [comment] 2021-08-08 14:19
> - In camera (7).webm where is the video from? Just trying to get the same input.

USB Web camera.

> - Have you had this issue since I fixed the private data?
I have not yet tested after the private data fix. I will download and test at least a few dozen times today.

> I wonder if I should be using the timestamp properties on the WebCodec output at all but instead count the buffers?

Try both and determibe which is more accurate based on results. I am skeptical about WebCodecs implementation at this stage. There are several outstanding issues that would perhaps continue if not for testing claims made in the specification and Chromium implementation using tip-of-tree build.

**Comment by davedoesdev** [comment] 2021-08-08 14:36
I want to look at WebTransport soon for a different project. How are you finding it? Have you tested backpressure (flow control) on an individual stream basis (i.e. can one stream starve the rest by not reading its data)?

**Comment by davedoesdev** [comment] 2021-08-08 14:43
I've just noticed the duration of encoded audio and video chunks is always 0

**Comment by davedoesdev** [comment] 2021-08-08 15:14
Timestamps seem consistent (comparing input and output to encoder).

Duration being 0 means I won't be telling libwebm a duration. It seems to be able to cope with that.

**Comment by guest271314** [comment] 2021-08-08 15:16
> I want to look at WebTransport soon for a different project. How are you finding it? 

https://github.com/aiortc/aioquic/pull/216, https://github.com/GoogleChrome/samples/pull/733.

It has been an interesting experience testing the deprecated `QuicTransport` and current `WebTransport` over HTTP/3 implementations.

I was banned from blink-dev for pointing out the flaw in deprecating `QuicTransport`/`quic-transport` before HTTP/3 server was implemented. 

I am currently streaming STDOUT from `espeak-ng` to the browser and either using `AudioWorklet` or WebCodecs to output audio, e.g., 

```
class AudioStream {
  constructor({ stdin, recorder = false }) {
    if (!/^espeak-ng/.test(stdin)) {
      throw new Error(`stdin should begin with "espeak-ng" command`);
    }
    this.command = stdin;
    this.url = 'https://localhost:4433/counter';
    this.transport = new WebTransport(this.url);
    this.readOffset = 0;
    this.duration = 0;
    this.channelDataLength = 440;
    this.sampleRate = 22050;
    this.numberOfChannels = 1;
    this.init = false;
    this.ac = new AudioContext({
      latencyHint: 0,
    });
    this.ac.suspend();
    this.msd = new MediaStreamAudioDestinationNode(this.ac, {
      channelCount: this.numberOfChannels,
    });
    this.inputController = void 0;
    this.inputStream = new ReadableStream({
      start: (_) => {
        return (this.inputController = _);
      },
    });
    this.inputReader = this.inputStream.getReader();
    const { stream } = this.msd;
    this.stream = stream;
    const [track] = stream.getAudioTracks();
    this.track = track;
    this.osc = new OscillatorNode(this.ac, { frequency: 0 });
    this.processor = new MediaStreamTrackProcessor({ track });
    this.generator = new MediaStreamTrackGenerator({ kind: 'audio' });
    const { writable } = this.generator;
    this.writable = writable;
    const { readable: audioReadable } = this.processor;
    this.audioReadable = audioReadable;
    this.audioWriter = this.writable.getWriter();
    this.mediaStream = new MediaStream([this.generator]);
    if (recorder) {
      this.recorder = new MediaRecorder(this.mediaStream);
      this.recorder.ondataavailable = ({ data }) => {
        this.data = data;
      };
    }
    this.outputSource = new MediaStreamAudioSourceNode(this.ac, {
      mediaStream: this.mediaStream,
    });
    this.outputSource.connect(this.ac.destination);
    this.resolve = void 0;
    this.promise = new Promise((_) => (this.resolve = _));
    this.osc.connect(this.msd);
    this.osc.start();
    this.track.onmute = this.track.onunmute = this.track.onended = (e) =>
      console.log(e);
    this.abortable = new AbortController();
    const { signal } = this.abortable;
    this.signal = signal;
    this.audioReadableAbortable = new AbortController();
    const { signal: audioReadableSignal } = this.audioReadableAbortable;
    this.audioReadableSignal = audioReadableSignal;
    this.audioReadableSignal.onabort = (e) => console.log(e.type);
    this.abortHandler = async (e) => {
      try {
        await this.disconnect(true);
      } catch (err) {
        console.warn(err.message);
      }
      console.log(
        `readOffset:${this.readOffset}, duration:${this.duration}, ac.currentTime:${this.ac.currentTime}`,
        `generator.readyState:${this.generator.readyState}, audioWriter.desiredSize:${this.audioWriter.desiredSize}`,
        `inputController.desiredSize:${this.inputController.desiredSize}, ac.state:${this.ac.state}`
      );
      this.resolve('Stream aborted.');
    };
    this.signal.onabort = this.abortHandler;
  }
  async disconnect(abort = false) {
    if (abort) {
      this.audioReadableAbortable.abort();
    }
    this.msd.disconnect();
    this.osc.disconnect();
    this.outputSource.disconnect();
    this.track.stop();
    try {
      await this.audioWriter.close();
      await this.audioWriter.closed;
      await this.inputReader.cancel();
    } catch (err) {
      throw err;
    }
    this.generator.stop();
    if (this.recorder && this.recorder.state === 'recording') {
      this.recorder.stop();
    }
    return this.ac.close();
  }
  async start() {
    return this.webTransportStream();
  }
  async abort() {
    this.abortable.abort();
    return this.promise;
  }
  async webTransportStream() {
    await this.transport.ready;   
    this.sender = await this.transport.createUnidirectionalStream();
    this.writer = this.sender.writable.getWriter();
    this.textEncoder = new TextEncoder('utf-8');
    this.inputData = this.textEncoder.encode(this.command);
    await this.writer.write(this.inputData);
    await this.writer.close();
    this.reader = this.transport.incomingUnidirectionalStreams.getReader();
    const result = await this.reader.read();
    this.transportStream = result.value;
    console.log(this.transport);
    this.stdout = this.transportStream.readable
    .pipeThrough(new TransformStream({
      start() {},
      transform(chunk, c) {
        c.enqueue(chunk);
      }, 
      async flush() {
        console.log('Done transforming WebTransport incomingUnidirectionalStreams');      
      }
    }));
    return this.audioStream();

  }
  async audioStream() {
    let channelData = [];
    try {
      await this.ac.resume();
      await this.audioWriter.ready;
      await Promise.allSettled([
        this.stdout.pipeTo(
          new WritableStream({
            write: async (value, c) => {
              let i = 0;
              if (!this.init) {
                this.init = true;
                i = 44;
              }
              for (; i < value.buffer.byteLength; i++, this.readOffset++) {
                if (channelData.length === this.channelDataLength) {
                  this.inputController.enqueue(
                    new Uint8Array(
                      channelData.splice(0, this.channelDataLength)
                    )
                  );
                }
                channelData.push(value[i]);
              }
            },
            abort(e) {
              console.error(e.message);
            },
            close: async () => {
              console.log('Done writing input stream.');
              if (channelData.length) {
                this.inputController.enqueue(new Uint8Array(channelData));
              }
              this.inputController.close();
            },
          }),
          { signal: this.signal }
        ),
        this.audioReadable.pipeTo(
          new WritableStream({
            async start() {
              await new Promise((resolve) => setTimeout(resolve, 100));
            },
            write: async ({ timestamp }) => {
              const { value, done } = await this.inputReader.read();
              if (done) {
                await this.inputReader.closed;
                try {
                  await this.disconnect();
                } catch (err) {
                  console.warn(err.message);
                }
                console.log(
                  `readOffset:${this.readOffset}, duration:${this.duration}, ac.currentTime:${this.ac.currentTime}`,
                  `generator.readyState:${this.generator.readyState}, audioWriter.desiredSize:${this.audioWriter.desiredSize}`
                );
                return await Promise.all([
                  new Promise((resolve) => (this.stream.oninactive = resolve)),
                  new Promise((resolve) => (this.ac.onstatechange = resolve)),
                ]);
              }
              const uint16 = new Uint16Array(value.buffer);
              // https://stackoverflow.com/a/35248852
              const floats = new Float32Array(this.channelDataLength / 2);
              for (let i = 0; i < uint16.length; i++) {
                const int = uint16[i];
                // If the high bit is on, then it is a negative number, and actually counts backwards.
                const float =
                  int >= 0x8000 ? -(0x10000 - int) / 0x8000 : int / 0x7fff;
                floats[i] = float;
              }
              const frame = new AudioData({
                format: 'f32-planar',
                sampleRate: 22050,
                numberOfChannels: 1,
                numberOfFrames: 220,
                timestamp,
                data: floats,
              });
              this.duration += (frame.duration / 10**6);
              if (this.recorder && this.recorder.state === 'inactive') {
                this.recorder.start();
              }
              await this.audioWriter.write(frame);
            },
            abort(e) {
              console.error(e.message);
            },
            close() {
              console.log('Done reading input stream.');
            },
          }),
          { signal: this.audioReadableSignal }
        ),
      ]);
      await this.transport.closed;
      this.resolve(
        this.recorder
          ? this.data && (await this.data.arrayBuffer())
          : 'Done streaming.'
      );
      return this.promise;
    } catch (err) {
      console.error(err);
      throw err;
    }
  }
}

var text = `So we need people to have weird new
ideas ... we need more ideas to break it
and make it better ...

Use it. Break it. File bugs. Request features.

- Real time front-end alchemy, or: capturing, playing,
  altering and encoding video and audio streams, without
  servers or plugins!
  by Soledad Penadés
   
von Braun believed in testing. I cannot
emphasize that term enough – test, test,
test. Test to the point it breaks.

- Ed Buckbee, NASA Public Affairs Officer, Chasing the Moon

Now watch. ..., this how science works.
One researcher comes up with a result.
And that is not the truth. No, no.
A scientific emergent truth is not the
result of one experiment. What has to
happen is somebody else has to verify
it. Preferably a competitor. Preferably
someone who doesn't want you to be correct.

- Neil deGrasse Tyson, May 3, 2017 at 92nd Street Y`;
var stdin = `espeak-ng -m --stdout "${text}"`;
var espeakng = new AudioStream({ stdin, recorder: false });
// espeakng.mediaStream: MediaStream containing MediaStreamTrack source output of espeak-ng --stdout
// var recorder = new MediaRecorder(espeakng.mediaStream);
// recorder.ondataavailable = ({ data }) => console.log(URL.createObjectURL(data));
// recorder.start();
// console.log(await espeakng.start());
// if (recorder.state === 'recording') recorder.stop();
var ab = await espeakng.start();
console.log(
  ab
);
```
and a modified version of the samples server code

```
                data = subprocess.run(split(input_data.decode()), stdout=subprocess.PIPE)               
                payload = data.stdout #str(self._counters[event.stream_id]).encode('ascii')
                self._http._quic.send_stream_data(
                    response_id, payload, end_stream=True)
                self.stream_closed(event.stream_id)
```
the issue I observe now is a connection lost error occurring between closing the stream and opening a new session even though `FIN` is passed to the method in the server and `closed` promise is fulfilled at client.

I will update https://github.com/guest271314/webtransport after a few more rounds of testing.

> I've just noticed the duration of encoded audio and video chunks is always 0

I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1235153 because I am currently de-serializing a serialized `EncodedAudioChunk` and then I need to get the `duration` from  `AudioData` after passing the `AudioDecoder.decode()` to avoid the audio rate described in this issue occurring - in between calls to `decode()`

```
let decoderController = void 0;
  const decoderStream = new ReadableStream({
    start(c) {
      return (decoderController = c);
    },
  });
  const decoderReader = decoderStream.getReader();
```

```
while (encoded.length) {
    const chunk = encoded.shift();
    chunk.data = new Uint8Array(base64ToBytesArr(chunk.data)).buffer;
    const eac = new EncodedAudioChunk(chunk);
    decoder.decode(eac);
    const { value: duration, done } = await decoderReader.read();
    // Avoid overflowing MediaStreamTrackGenerator
    // https://bugs.chromium.org/p/chromium/issues/detail?id=1184070
    // https://bugs.chromium.org/p/chromium/issues/detail?id=1199377 
    await new Promise((resolve) =>
      setTimeout(resolve, ((duration || 0) / 10 ** 6) * 900)
    );
  }
  // Avoid clipping end of playback
  await new Promise((resolve) =>
    setTimeout(resolve, (base_time / 10 ** 6 - audio.currentTime) * 1000)
  );
```

The authors of this CL https://chromium-review.googlesource.com/c/chromium/src/+/3077120 evidently did not interpret correctly what I was pointing out, based on the WPT test. The specification does not provide a means to pass `duration` to `EncodedAudioChunk` constructor, and that is not what was asked for. The `duration` should be set by the implementation, not the user, just like on `AudioData` object.

**Comment by guest271314** [comment] 2021-08-08 15:18
This is the de-serialization of `EncodedAudioChunk` code https://plnkr.co/edit/clbdVbhaRhCKWmPS?preview that will exhibit what is being described here in this issue, yet more pronounced, when duration is not magically derived by the user - the specification does not handle this.

**Comment by davedoesdev** [comment] 2021-08-08 15:28
This is the sort of stuff that should have been unit tested

**Comment by guest271314** [comment] 2021-08-08 15:31
I concur. If you read the relevant WPT test at https://chromium.googlesource.com/chromium/src/+/8909e5008cc1cb410b9c431f0bb8e25e968eacfb/third_party/blink/web_tests/external/wpt/webcodecs/encoded-audio-chunk.any.js#7

```
duration: 123,
```

it does not appear that the Chromium authors understood what the issue was describing.

**Comment by guest271314** [comment] 2021-08-08 15:33
Perhaps a different voice might be helpful. They just ban me.

I was not asking for a means to pass an arbitrary number to `EncodedAudioChunk()` constructor, I was asking for implementers to implement their own specification - to set the `duration` at construction internally.

**Comment by guest271314** [comment] 2021-08-08 15:38
If you remove 

```
    const { value: duration, done } = await decoderReader.read();
```

from the `while` loop 

and 

```
      decoderController.enqueue(frame.duration);
```

from `AudioDecoder.output` you will observe a similar "audio rate" increase as described in this bug, due to `MediaStreamTrackGenerator` not being capable of handling "overflow" and the resulting `AudioData` in the same callback being dissimilar from the input `AudioData` https://bugs.chromium.org/p/chromium/issues/detail?id=1237633.

**Comment by guest271314** [comment] 2021-08-08 15:42
For audio processing `AudioWorklet` https://github.com/guest271314/AudioWorkletStream is far more reliable, however that design suffers from being defined as a Ecmascript module which prevents loading the script on pages where CSP prohibits it https://github.com/WebAudio/web-audio-api-v2/issues/109, that is why I created https://github.com/guest271314/NativeTransferableStreams to work around that limitation.

**Comment by davedoesdev** [comment] 2021-08-08 17:51
I had wondered whether overflowing the encoder was causing the issue. IIRC
the decision was just to warn about it which isn't much use.

I think I'll open an issue about duration being 0.

**Comment by guest271314** [comment] 2021-08-08 17:54
I tested again several times using different microphone input devices
[webm-muxer-js-audio-rate.zip](https://github.com/davedoesdev/webm-muxer.js/files/6951242/webm-muxer-js-audio-rate.zip). The issue still occurs. The first couple times the code is used appears to when the rate is increased.

> I think I'll open an issue about duration being 0.

I would link to the issue I filed and make sure the owners of the component understand they misunderstood the issue I filed, and setting an optional `duration` at `EncodedAudioChunk` constructor is not useful - the implementation needs to set that (which should be the same whether the audio is encoded or decoded) per specification.

**Comment by davedoesdev** [comment] 2021-08-08 17:55
Actually I think that was media stream processing. Can the control message
queue of the webcodec encoders be given an unlimited number of messages?

**Comment by davedoesdev** [comment] 2021-08-08 17:56
OK thanks. Do you mean the first couple of times after the page is loaded?

**Comment by guest271314** [comment] 2021-08-08 18:04
> Actually I think that was media stream processing. Can the control message
queue of the webcodec encoders be given an unlimited number of messages?

Per the evidence, no. Not specified. https://github.com/w3c/mediacapture-transform/issues/20.


What we do know is that the `sampleRate` and duration of `AudioData` => `EncodedAudioChunk` => `AudioDeocoder` => `AudioData` are not 1:1.

WebCodecs 'opus' always encodes to 48000, even though `opusenc` provides `--raw-rate`.

WICG banned me from contributing to any repository which uses their handle. See https://github.com/w3c/webcodecs/pull/319

> The rate must be in [8, 12, 16, 24, 48] kHz

is not true and correct, which you can verify at command line with

```opusenc --raw-rate 22050 test.wav test.opus```

meaning that when I pass `22050` to `sampleRate` that should be set, though is not, the sample rate is always set to `48000`.

> OK thanks. Do you mean the first couple of times after the page is loaded?

Yes.

**Comment by guest271314** [comment] 2021-08-08 18:12
I will more than likely create a WebTransport version for `mkvmerge` and `opusenc` to avoid using WebCodecs 'opus' implementation, and loading WebAssembly modules in RAM (and Google "Safe Browsing" "scanning" files for alleged "malware" even though I deliberately turned off "Google Safe Browsing" at Settings and it is impossible for File System Access to execute a file - because the implementation always writes a new file and removes executable permissions, et al. https://bugs.chromium.org/p/chromium/issues/detail?id=1228068) - just use the native application with the pattern I use for `espeak-ng`: STDIN (browser) => WebTransport (native application and shell scripts)=> STDOUT (browser).

**Comment by guest271314** [comment] 2021-08-08 18:23
If you read the code in `AudioStream` at https://github.com/davedoesdev/webm-muxer.js/issues/6#issuecomment-894812377 what I do to maintain 1 channel, 22050 `sampleRate` is to "piggyback" on the output of an Web Audio API `OscillatorNode` with `frequency` set to `0`, passed to a `MediaStreamAudioDestinationNode`, then when reading the `readable` from `MediaStreamTrackProcessor` substitute the constructed `AudioData`.

**Comment by guest271314** [comment] 2021-08-08 18:32
Before `AudioFrame` with `AudioBuffer` passed was deprecated I was able to get the `AudioFrame` from `AudioDecoder.output` and construct smaller `AudioFrame`s - because the `AudioData` and previously implemented `AuduioFrame` from `AudioDecoder.output` have more frames and longer duration than input . That is non-trivial with `copyTo()`, at least I have not achieved a workaround, yet. See, again https://bugs.chromium.org/p/chromium/issues/detail?id=1237633, https://plnkr.co/edit/sEupuQ2pYepXQcV6?preview, also https://github.com/xiph/opus/issues/221.

**Comment by guest271314** [comment] 2021-08-08 18:50
The code at https://github.com/WebAudio/web-audio-api-v2/issues/133 demonstrates the problem of changing `sampleRate` and inability to get the data using `copyTo()` to "downmix" the frames and play at a Web Audio API - without garbled output.

**Comment by davedoesdev** [comment] 2021-08-08 19:21
@guest271314 Would it be possible to make the following change:

```diff
diff --git a/encoder-worker.js b/encoder-worker.js
index 0a0b449..ee1b5d4 100644
--- a/encoder-worker.js
+++ b/encoder-worker.js
@@ -18,6 +18,9 @@ onmessage = async function (e) {
                 if (msg.config.codec !== 'pcm') {
                     encoder = new Encoder({
                         output: chunk => {
+                            if (msg.audio) {
+                                console.log("OUT", chunk.timestamp, chunk.duration);
+                            }
                             const data = new ArrayBuffer(chunk.byteLength);
                             chunk.copyTo(data);
                             self.postMessage({
@@ -47,6 +50,7 @@ onmessage = async function (e) {
                     }
                     if (msg.audio) {
                         if (encoder) {
+                            console.log("IN", result.value.timestamp, result.value.duration, result.value.sampleRate, result.value.allocationSize({ planeIndex: 0}));
                             encoder.encode(result.value);
                         } else {
                             const options = { planeIndex: 0 };
```

and paste the log lines here for when you get a repro of this issue please? I just want to rule out the data from the media capture APIs.

**Comment by guest271314** [comment] 2021-08-08 19:35
Ok.

**Comment by guest271314** [comment] 2021-08-08 21:16
I cannot predict when the rate increase will occur.

For "camera.webm"

this is the result of creating an `AudioBuffer` with `BaseAudioContext.decodeAudioData()` 

```
AudioBuffer {length: 55565, duration: 1.2599773242630385, sampleRate: 44100, numberOfChannels: 1}
```
when setting the `src` of HTML `<audio>` element the duration is `3.588`.

**Comment by guest271314** [comment] 2021-08-08 21:19
This is output from a run where rate is not increased

```
encoder-worker.js:53 IN 1258829658268 10000 48000 1920
encoder-worker.js:53 IN 1258829668270 10000 48000 1920
encoder-worker.js:53 IN 1258829678267 10000 48000 1920
encoder-worker.js:53 IN 1258829688263 10000 48000 1920
encoder-worker.js:53 IN 1258829698266 10000 48000 1920
encoder-worker.js:53 IN 1258829708265 10000 48000 1920
encoder-worker.js:22 OUT 1258829648275 0
```

Note that `duration` is `0`.

**Comment by davedoesdev** [comment] 2021-08-10 05:39
I've filed https://bugs.chromium.org/p/chromium/issues/detail?id=1238217

Without the duration I can't switch to ignoring the timestamps and make my own "clock". I wanted to try that in case the timestamp generation from the AudioEncoder is buggy and causing the audio rate changes.

**Comment by guest271314** [comment] 2021-08-10 06:10
See https://bugs.chromium.org/p/chromium/issues/detail?id=1237633, https://chromium-review.googlesource.com/c/chromium/src/+/3077120.

**Comment by davedoesdev** [comment] 2021-08-10 06:27
Yep, Chrome's WebCodecs implementation needs some attention.

I linked to https://bugs.chromium.org/p/chromium/issues/detail?id=1235153 in my ticket.

**Comment by guest271314** [comment] 2021-08-10 07:49
`AudioData` => `AudioEncoder` => `AudioDecoder` => `AudioData` 

currently results in different, dissimilar input => output `AudioData` (`sampleRate`, `format`, `duration`)

```
(async () => {
  const ac = new AudioContext({
    sampleRate: 22050,
    latencyHint: 0,
  });
  const msd = new MediaStreamAudioDestinationNode(ac, {
    channelCount: 1,
  });
  const [track] = msd.stream.getAudioTracks();
  const { kind } = track;
  const osc = new OscillatorNode(ac, { frequency: 0 });
  osc.connect(msd);
  const processor = new MediaStreamTrackProcessor({ track });
  const { readable } = processor;
  const [a, b] = readable.tee();
  const generator = new MediaStreamTrackGenerator({ kind });
  const { writable } = generator;

  const promises = [];

  let decoded = 0;
  let transformed = 0;
  const config = {
    numberOfChannels: 1,
    sampleRate: 22050,
    codec: 'opus',
    bitrate: 16000,
  };
  const encoder = new AudioEncoder({
    error(e) {
      console.error(e);
    },
    output(chunk, metadata) {
      if (metadata.decoderConfig) {
        decoder.configure(metadata.decoderConfig);
        console.log({ metadata });
      }
      decoder.decode(chunk);
    },
  });
  encoder.configure(config);
  const decoder = new AudioDecoder({
    error(e) {
      console.error(e);
    },
    async output(audioData) {
      promises.push({ decoded: audioData });
      ++decoded;
    },
  });
  let _controller;
  await Promise.allSettled([
    a
      .pipeThrough(
        new TransformStream({
          start(_) {
            transformController = _;
          },
          async transform(audioData, controller) {
            promises.push({ transformed: audioData.clone() });
            ++transformed;
            if (decoded >= 2) {
              _controller.error();
              controller.terminate();
            }
            controller.enqueue(audioData);
          },
          async flush() {
            console.log('flush');
          },
        })
      )
      .pipeTo(writable),

    b.pipeTo(
      new WritableStream({
        start(_) {
          _controller = _;
        },
        async write(audioData, controller) {
          encoder.encode(audioData);
        },
      })
    ),
  ]);

  console.log(promises);
  console.log('decoded:');
  const d = promises.filter((v) => 'decoded' in v);
  d.map(console.table);
  console.log('transformed:');
  const t = promises.filter((v) => 'transformed' in v);
  t.map(console.table);
  console.log('sampleRate:');
  console.assert(d[0].decoded.sampleRate === t[0].transformed.sampleRate, [
    d[0].decoded.sampleRate,
    t[0].transformed.sampleRate,
  ]);
  console.log('duration:');
  console.assert(d[0].decoded.duration === t[0].transformed.duration, [
    d[0].decoded.duration,
    t[0].transformed.duration,
  ]);
  console.log('format:');
  console.assert(d[0].decoded.format === t[0].transformed.format, [
    d[0].decoded.format,
    t[0].transformed.format,
  ]);
  console.table(await AudioEncoder.isConfigSupported(config));
  await encoder.flush();
  await decoder.flush();
  await ac.close();
})().catch(console.error);
```

**Comment by guest271314** [comment] 2021-08-11 04:59
See https://chromium-review.googlesource.com/c/chromium/src/+/3084018. Per source code output 

https://chromium.googlesource.com/chromium/src/+/49cf62132c057a79b093c8b5ab72f195cac447cc/media/audio/audio_opus_encoder.cc#32

```
// For Opus, we try to encode 60ms, the maximum Opus buffer, for quality
// reasons.
constexpr int kOpusPreferredBufferDurationMs = 60;
```



and `48000` sample rate is fixed https://chromium.googlesource.com/chromium/src/+/49cf62132c057a79b093c8b5ab72f195cac447cc/media/audio/audio_opus_encoder.cc#58

```
// default preferred 48 kHz. If the input sample rate is anything else, we'll
// use 48 kHz.
```

**Comment by davedoesdev** [comment] 2021-08-11 06:53
Thanks. With a duration I can try ignoring the timestamps on the encoded audio data.

I've also found that supplying a stereo sample to `--use-file-for-fake-audio-capture` while manifesting in two channels of audio in Chrome, both channels are the same. Have you done anything with 2 channel audio?

**Comment by guest271314** [comment] 2021-08-11 14:16
`--use-file-for-fake-audio-capture` is intended for 1 channel input for testing.

For capturing system audio output I process 2 channel PCM from `parec` at https://github.com/guest271314/captureSystemAudio/blob/3fc5a584f4085bcb2e41075238bbfaecbec4701a/native_messaging/capture_system_audio/audioStream.js#L140-L165

**Comment by guest271314** [comment] 2021-08-11 14:22
It is probably less work just using `opusenc` and `opusdec` for encoding and decoding given the hard coded restrictions on sample rate and duration.

**Comment by davedoesdev** [comment] 2021-08-11 20:38
The ultimate use I have for this project is to stream to YouTube using just a browser so using native code (though better) is out for me

**Comment by guest271314** [comment] 2021-08-12 00:42
See https://blog.rillke.com/opusenc.js/

**Comment by davedoesdev** [comment] 2021-08-13 07:42
I've just pushed b0e7b71d3a4f3d1d1eb66a46b4c85d0c9b834716 which prefers duration over timestamp on encoded audio chunks. Maybe this fixes this occasional audio rate change issue?

You'll need Chrome 94.0.4606.0 or later to get the durations.

**Comment by guest271314** [comment] 2021-08-13 14:09
I cannot consistently reproduce the bug, I have reproduced it at least three times intermittently. 

From my perspective part of the issue is Chrome internally sets sample rate to 48000 for 'opus' encoding which is an explanation for the faster rate of playback.

You can close this issue if you want, since you have not reproduced it. I would keep this edge case in mind moving forward. 

FWIW I posted the code I am currently using for resampling the 48000 to 22050 at https://github.com/WebAudio/web-audio-api-v2/issues/133#issuecomment-897651565. As I stated there, the quality is sub-par per my standards.

**Comment by davedoesdev** [comment] 2021-08-14 05:48
@guest271314 thanks for your help, let me know if you ever encounter this issue again. There should be logging in now which will warn if the durations don't match the timestamps.

**Closed as completed** 2021-08-14 05:47 UTC
